name: Generate PR Description

on:
  pull_request:
    types: [opened]

jobs:
  generate_description:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Python dependencies
        run: pip install -r .config/scripts/requirements.txt

      - name: Run script
        env:
          OPENAI_API_KEY: {% raw %}${{ secrets.OPENAI_TOKEN }}{% endraw %}
          GITHUB_TOKEN: {% raw %}${{ secrets.GH_TOKEN }}{% endraw %}
          REPO_NAME: {% raw %}${{ github.repository }}{% endraw %}
          PR_NUMBER: {% raw %}${{ github.event.pull_request.number }}{% endraw %}
        run: |
          python .config/scripts/generate_pr_description.py