name: Change Tracking Marker
on:
  release:
    types: [published]

jobs:
  newrelic:
    runs-on: ubuntu-latest
    name: New Relic
    steps:
      # This step builds a var with the release tag value to use later
      - name: Set Release Version from Tag
        run: echo "RELEASE_VERSION={% raw %}${{ github.ref_name }}{% endraw %}" >> $GITHUB_ENV
      # This step creates a new Change Tracking Marker
      - name: New Relic Application Deployment Marker
        uses: newrelic/deployment-marker-action@v2.3.0
        with:
          apiKey: {% raw %}${{ secrets.NEW_RELIC_API_KEY }}{% endraw %}
          guid: {% raw %}${{ secrets.NEW_RELIC_DEPLOYMENT_ENTITY_GUID }}{% endraw %}
          version: "{% raw %}${{ env.RELEASE_VERSION }}{% endraw %}"
          user: "{% raw %}${{ github.actor }}{% endraw %}"
