definitions:
  entities.LoginResponseEntity:
    description: LoginResponseEntity model data
    properties:
      accessToken:
        description: Token to access this API
        type: string
      expiresIn:
        description: Time to expires token in int
        type: integer
      refreshToken:
        description: Token to refresh Access Token
        type: string
    type: object
  entities.RequestLoginEntity:
    description: RequestLoginEntity model data
    properties:
      email:
        description: User email
        type: string
      password:
        description: User password
        type: string
    type: object
  utils.HttpError:
    properties:
      code:
        type: integer
      error:
        type: string
      message:
        type: string
    type: object
info:
  contact: {}
paths:
  /login:
    post:
      consumes:
      - application/json
      description: performs login of user
      parameters:
      - description: Login Data
        in: body
        name: _
        required: true
        schema:
          $ref: '#/definitions/entities.RequestLoginEntity'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.LoginResponseEntity'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.HttpError'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/utils.HttpError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.HttpError'
      summary: Validate login
      tags:
      - login
swagger: "2.0"
